### ISSUE TITLE
How to avoid: reached server, but there are still pending connections?

### ISSUE THREAD

**Issue by quesurifn** [rubycdp/ferrum#122]
Hello, 

I currently am scraping monster with Ferrum. I keep hitting this problem here. What would be the easiest way to avoid this? 

Code sample below:

 ```
def scrape_monster
		browser = Ferrum::Browser.new
    browser.goto(MONSTER_URL)
    browser.network.wait_for_idle(:timeout => 100)
    body = JSON.parse(ActionView::Base.full_sanitizer.sanitize(browser.body))

    urls_to_query = []
    jobs = []

    body.each do |job|
      urls_to_query << job unless !job.key?('Title')
    end

    urls_to_query.each do |obj|
      browser.goto(obj["JobViewUrl"])
      browser.network.wait_for_idle(:timeout => 100)
      script_tag = browser.at_css('script[type="application/ld+json"]').text

      puts script_tag
      json = JSON.parse(script_tag)

      job = {}
      job[:date_posted] = json['datePosted']
      job[:description] = ActionView::Base.full_sanitizer.sanitize(json['description'])
      job[:description_html] = json['description']
      job[:company] = json['hiringOrganization']['name']
      job[:title] = json[:title]
      job[:original_url] = obj['JobViewUrl']
      job[:orig_id] = obj['JobViewUrl'].split('/').last
      job[:location] = json['jobLocation']['addressRegion']
      job[:category] = json.key?('occupationalCategory') ? obj['occupationalCategory'][0].split(':')[1] : nil
      job[:source] = "monster"

      jobs << job

      sleep rand(10)
    end
    browser.quit
    jobs
  end
```

**Comment by IlkhamGaysin** [comment]
Having the same issue with cuprite and capybara on top.

**Comment by IlkhamGaysin** [comment]
Sometimes turning Chrome helps, but I'm not sure it's related to that.

**Comment by route** [comment]
I think you have to find out what is blocking Chrome, sometimes some resources are really slow and crucial for the app, other times you can aviod loading them and it's fine. It all depends on the website, but I'd suggest blacklisting all the resources you don't consider important and see the impact.

**Comment by alexanderadam** [comment]
> sometimes some resources are really slow and crucial for the app

In that case it would be good to have an option for "close open/stale connections after xx seconds". Or even better: retries.

Also I'm wondering why it's not running into some kind of timeout exception.

**Comment by route** [comment]
The thing is Chrome doesn't provide details about such resources. I remember one bug because of such behavior, Chrome was waiting for such connection even more than 30s, more than timeout Ferrum uses and thus didn't send a crucial event Ferrum was reling on. I tried to find any setting for such behaviour without any luck. I'm afraid here we have similar situation, I would set socket connect timeout for all sockets in Chrome to 5-10s and read timeout to Ferrums default, but...

**Comment by alexanderadam** [comment]
Okay, then maybe a different approach:

If I understand this correctly Puppeteer doesn't wait for finished connections and [you even have to use another dependency](https://github.com/jtassin/pending-xhr-puppeteer) if you want it to wait.

So what if ferrum ignores these kind of errors and it would just have an optional block that is yielded if given and all connections are finished?

**Comment by route** [comment]
Sounds good in general but you have to keep in mind that Cuprite depends on Ferrum as many projects by now, I would keep current behaviour as default and if another one works fine I'd make it optional I guess. Thoughts?

**Comment by evilcins** [comment]
Having this issue as well, getting:
```
Ferrum::StatusError:
       Request to http://mbp.local:50180/path reached server, but there are still pending connections: http://mbp.local:50180/path
```

**Comment by gdomingu** [comment]
@IlkhamGaysin I'm also having this issue with cuprite and capybara. Did you ever get it worked out?

**Comment by IlkhamGaysin** [comment]
@gdomingu it works for me mostly but sometimes it fails...

**Comment by gdomingu** [comment]
I wasn't actually to get to the bottom of it, but I did try the old "turn computer off and on again" and it fixed it for me.

**Comment by MartinsLapsa** [comment]
Having same issue using Cuprite. Retry usually succeeds.

**Comment by colinbrogan** [comment]
Any more ideas on this? I am having the same problem, usually with image files I don't even need chrome to load (because I am running headless). I am trying to pass command line settings to disable images, or send the request as Connection: close, and none of it seems to work. Ofcourse, reloading a few times, one of the requests will make it. But I am trying to find a solution which is reliable every time.

**Comment by colinbrogan** [comment]
Wanted to share with everyone the workaround I used to fix my specific issue.
Before my goto method call, I added the following code:
`
        browser.network.intercept
        browser.on(:request) do |request|
	        if request.match?(/\.png|\.jpg|\.jpeg|\.svg|\.woff2|\.css/)
		  	puts ("Aborting request "+request.url.to_s)
		        request.abort
	        else
	                puts("Continue with "+request.url.to_s)
			request.continue
		end
	end
	browser.goto( my_url )

`

Basically, with the regular expressions, you setup a function to match and block any extra page dependencies you don't need before running your request. In my case, I don't need any images or font files or css, because I am running headless, and just trying to scrape the html. The puts lines can also help you debug your regular expressions, by showing you live which files you are allowing verses blocking on any given page load.
This method allowed me to rapidly increase the time it took to output request html (which was all I needed), while preventing all these timeout errors.

**Comment by route** [comment]
I added `pending_connection_errors` to https://github.com/rubycdp/ferrum#customization though I don't recommend turning it off. I understand that in certain circumstances it can be annoying, but it's a very rare case. Things to consider before turning it off:

1. If request is to your local server figure out why it's so slow
2. If request is to external server try to block such if it's not vital part of your app
3. Try to increase `:timeout`, because if timeout is reached and there are still pending connection the error is raised.
4. If it's rails assets, try to pre-compile them or remove debugging https://guides.rubyonrails.org/asset_pipeline.html#turning-debugging-off option so that instead of getting 1 file rails splits into many increasing number of requests.
5. Change your WebServer in Capybara
6. Give up

**Comment by blocknotes** [comment]
I had the same issue with a test in CI that uses Capybara and Ruby 3.0.

The test was making a JS check using `Capybara.evaluate_script(code)` - I replaced that part with:

```rb
    browser = page.driver.browser
    browser.evaluate(code)
```

It works as expected now.
