### ISSUE TITLE
Configurable GOTO_WAIT setting

### ISSUE THREAD

**Issue by nickhammond** [rubycdp/ferrum#179]
Hi there,

Loving Ferrum! 

I noticed that there's a constant([`Ferrum::Page::GOTO_WAIT`](https://github.com/rubycdp/ferrum/blob/3a2dc276ba312831487b05cb6e176cae5a7375a4/lib/ferrum/page.rb#L17)) that fetches from ENV but isn't configurable or mentioned by the regular browser setup functionality or anywhere really. Looking at the [commit history](https://github.com/rubycdp/ferrum/commit/65a249ceff4aed70148f9aeddb4e0ba1c4442d0f#diff-2f9537c613f48bed5ff6ca273e2dac28886a32fe78dcd2dc7c7c798c891434d3R70) it looks like it used to utilize the [`timeout`](https://github.com/rubycdp/ferrum/blob/3a2dc276ba312831487b05cb6e176cae5a7375a4/lib/ferrum/page.rb#L65) method which fetched the timeout value from the browser.

Is this intentional or is there any interest in bubbling this up as an additional option? I'm using Ferrum to download some files and sometimes they take a bit of time to download and that's fine. It looks like `GOTO_WAIT` is only used in the `go_to` function so maybe we could add a keyword argument for `wait` or `timeout` to that method. Something like `def go_to(url = nil, wait: GOTO_WAIT)`

**Comment by route** [comment]
Sorry for a late response, this is sounds good to me.

**Comment by route** [comment]
Actually I went trough the implementation and I was wrong. Timeout is the king.

All commands in Ferrum have timeout to prevent possible deadlocks. When you send a command to the browser by the websocket we always wait a response for given amount of time (`:timeout` option), if there's no response (browser can be dead) we raise error, if there's then all's good.

There are commands that can initiate page/frame reloading, there are some that don't. For such commands we should wait a bit for events to occur (e.g. frame reloading). `go_to` is one of them. When you call `go_to` you can supply an anchor which means frame won't be reloaded or you can pass a new url which of course reloads a page. In other words this `GOTO_WAIT` is just for internal use and thus so small 0.1 by default, but you should utilize timeout for the whole browser or per page. It is exactly what you need because `go_to` returns back to you only when the page/frame is fully loaded.
