### ISSUE TITLE
Chromium 72

### ISSUE THREAD

**Issue by haroldsultan** [rubycdp/ferrum#194]
I am trying to use a chromium binary that is included on a node as part of puppeteer 
```
browser = Ferrum::Browser.new(browser_path: 'LOCAL_PATH TO CHROME V72')
browser.go_to("some site")
element = browser.at_css('input[name="NAME"]')
```
I am getting Ferrum::JavaScriptError: SyntaxError: Unexpected token =

```
browser = Ferrum::Browser.new(browser_path: 'LOCAL_PATH TO CHROME V93')
browser.go_to("some site")
element = browser.at_css('input[name="NAME"]')
```
works

**Comment by route** [comment]
I'm afraid even if there's such a difference in Chrome versions, Ferrum is not going to include hacks for older versions. The protocol is evolving rapidly and we need to keep up with speed rather than try to fix something like this. Downloading up to date Chrome should always be preferable. Sorry :(
