### ISSUE TITLE
 private method `puts' called for #<Logger:???> (NoMethodError), when use logger option with ruby 3.0

### ISSUE THREAD

**Issue by zw963** [rubycdp/ferrum#200]
https://github.com/rubycdp/ferrum/blob/master/lib/ferrum/browser/web_socket.rb#L80

Above line raise error when use when ruby 3.0, and set logger as 

```rb
Ferrum::Browser.new(
      logger: Logger.new('chrome_headless.log', 10, 1024000), 
      headless: true)
```

ruby/3.0.0/gems/ferrum-0.11/lib/ferrum/browser/web_socket.rb:80:in `send_message': private method `puts' called for #<Logger:0x0000000003ed17e8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000003ed0208 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000003ecb500 @shift_period_suffix="%Y%m%d", @shift_size=1024000, @shift_age=10, @filename="chrome_headless.log", @dev=#<File:chrome_headless.log>, @binmode=false, @mon_data=#<Monitor:0x0000000003ecbcf8>, @mon_data_owner_object_id=3060>> (NoMethodError)

**Comment by Mifrill** [comment]
> Sorry, i consider this make a simple issue became more complicated, right?

No. I see no issue here, actually. Just try to use the object that responds to puts, like `StringIO.new`

> logger option, it quite intuitive to pass in a ruby logger object, right?

No. Gem is expecting for a logger that:
> :logger (Object responding to puts) - When present, debug output is written to this object.

> maybe we can add a if/else, to support a Logger object, or ducking type check info method?

I don't think it is a good way to go because it's not a gem responsibility to maintain different types/kinds of loggers, that's why we put a predicted interface for the logger object.

**Comment by Mifrill** [comment]
it's a guard, in case of "no logger provided", for example:
https://github.com/rubycdp/ferrum/blob/006c5fc385596c218402de8b0d24dbe6739f1c72/lib/ferrum/browser/process.rb#L148
is quite similar to:
```ruby
@logger&.puts(output)
```
because of ampersand:
```ruby
irb(main):001:0> nil&.whatever?
=> nil
```
More details: https://stackoverflow.com/questions/36812647/what-does-ampersand-dot-mean-in-ruby

**Comment by zw963** [comment]
> it's a guard, in case of "no logger provided",

Got it, thank you.

**Comment by Mifrill** [comment]
@route looking at the issue title:
> private method `puts' called for #<Logger:???> (NoMethodError), when use logger option with ruby 3.0

I think we can close this one, as no issue here.
If we plan to rewrite the logger to make it more friendly, I think it's nice to create a new issue as enhancement and put a note with the reference for this one, what do you think?
