### ISSUE TITLE
Thread safety concerns with Proxy

### ISSUE THREAD

**Issue by ttilberg** [rubycdp/ferrum#209]
The readme currently states that Ferrum is fully threadsafe. Is this still the case with the new proxy option? Since `browser.proxy_server.rotate` affects global state, I'm just curious if this warrants any special handling or notes in the readme.

**Comment by route** [comment]
It's thread safe because both Ferrum and HTTPProxy are thread safe, the issue is when you have multiple pages they still use the same http proxy, so they can end up using the same IP with dumb webrick proxy. But with smart rotating proxy that can determine sessions and switch proxies after some time it would work much better.
