### ISSUE TITLE
Is there exist a way to capture the node node_id changes?

### ISSUE THREAD

**Issue by zw963** [rubycdp/ferrum#224]
Following is some code for describe this issue.

```rb
    loop do
      more_link=instance.at_xpath('.//span[contains(text(), "更多")]')
      puts more_link.node_id
    end
```
Will get like following:

```
179
179
179
179
179
179
179
179
179
179
179
179

...

179
179
283
283
283
283
283
283
283
283
...

```

We can see node_id from 179 change to 283 when page loading.

so, if there is a way to capture this changes, and auto find the newest node(283)
when old node(179) invalid?

Thank you.

**Comment by route** [comment]
I have opposite question. Why do you need to watch node id?

**Comment by zw963** [comment]
> I have opposite question. Why do you need to watch node id?

Because when i try to find node use `node = instance.at_xpath('.//span[contains(text(), "更多")]')`, it get the first(179) node,  then after page is loaded, when i want to visit this node again, always get `No node with given id found` error.

For now, i have to do like this:

```
instance.goto url

loop do
        more_link=instance.at_xpath('.//span[contains(text(), "更多")]') 
        if (more_link.moving? rescue nil)   # => more_link.moving?  keep raise exception until it retreive 283
          more_link.click                             # => util more_link.moving? return true, i can click it now.
          break
        end
        sleep 0.5
      end
```

Above solution works anyway, but i curious if i do somethings wrong, i am still confusing about when to use `instance.network.wait_for_idle`, and when to use `node.wait_for_stop_moving`, because both of them not work.

Thank you.

**Comment by route** [comment]
I got your pain. First to answer your questions, remember that we are working in fully asynchronous world. When you call `go_to` and the result is returned it doesn't really mean the page stays static and "fully" loaded. What I mean is yes page is loaded, all html/css/js files are loaded, but it really doesn't mean that JS will not initiate AJAX requests or Websocket which in turn can change the page drastically. So even when page is loaded there might be some connections still opened (AJAX connections).

`network.wait_for_idle` can be used if you expect page to stop all outgoing AJAX connection at some point, if page constantly fetches something here and there it wont help of course.

`node.wait_for_stop_moving` can be used if we are going to click node which is moving or changing it's position, in fact it's actually called internally when you call `node.click` method to prevent misclicking. In order to click node we need to find its coordinates and sometimes when we found position and try to click by (x,y) the node can be gone, remember it's JS and everything is async.

To answer your original question. Imagine that we found node by `node = xpath("...")` now we have node in Ruby world but in the browser something might happen and node can disappear, so now we are in position of having node in Ruby but not having it on the page. I might implement something to catch node changes in mark node as stale but the only thing that would change is error name because the node in Ruby is still invalid.

Instead of catching this I think you better take a look at your script at different angle. I think you start interacting with page kinda "too early" what about:

```ruby
browser.go_to(url)
browser.network.wait_for_idle
if browser.at_xpath("find element that is signaling that page is "fully" loaded")
  browser.at_xpath('.//span[contains(text(), "更多")]').click
  ...
end
```

**Comment by zw963** [comment]
I get the point, thank you very much!

**Comment by zw963** [comment]
@route , BTW, is there exist a method, seem like `record.reload!` in Active Record,  try to retrieve the latest page element, but reuse old css/xpath matcher?

**Comment by route** [comment]
no there's no such

**Comment by zw963** [comment]
> no there's no such

```
more_link=instance.at_xpath('.//span[contains(text(), "更多")]')
# ...
more_link.reload.click  # rerun above xpath when this ruby object is invalid, or just return valid object, then click.
                                     # if this object not retrieve from a exactly matcher (e.g. at_xpath, at_css),  raise exception.
                                     
```

Do you consider if this is a useful way to resolve this issue?

**Comment by route** [comment]
I think there's no 1 on 1 mapping between node and css/xpath. In general css/xpath returns a collection which can be empty not a single node, and one node can be found using multiple css/xpaths. So really it's idiomatically incorrect. I can have two identical nodes queried by two different xpaths. The problem is broader than that and I need to address stale nodes first, but it requires investigation and is time consuming, so don't expect any solution soon.

**Comment by route** [comment]
You better write a failing test and mark it skipped, I'll merge it and we will have failing test for future investigation
