### ISSUE TITLE
connecting to existing session always creates a new window

### ISSUE THREAD

**Issue by matti** [rubycdp/ferrum#34]
with
```
browser = Ferrum::Browser.new({
  url: "http://localhost:9222",
})
browser.goto "https://google.com"
```
a new window is created - is it possible to re-use the existing window?

also
```
browser.quit
```
does not close the created window

**Comment by route** [comment]
I assume that you use `headless: false` because you didn't say it, but you can't create tabs in the existing window you have to create new context and target which basically means new window in incognito mode, the default one is not accessible by default. `quit` doesn't work because this process can be created on a different machine so the process that started the browser should call it. You should call `browser.page.close`

**Comment by Ararat777** [comment]
Sorry to continue this issue. First of all, I would like to thank you for this wonderful gem :). But my question is, is it possible to continue working in an already running instance?
For example:
`browser = Ferrum::Browser.new`
`browser.goto("https://google.com")`
`same_browser =  Ferrum::Browser.new(url: "http://#{host}:#{port}") # Host and port of the running instance`

And after that continue the work further:
`same_browser.at_css("#search").type("Something")`

Thank you

**Comment by route** [comment]
I don't think it's safe there are some important events that Chrome sends when calling `goto` and if there's only one websocket connection it will be send only to 1 page instance instead of 2.

```ruby
browser = Ferrum::Browser.new
page = browser.page
target_id = page.target_id

# on another machine
same_browser = Ferrum::Browser.new(url: ...)
same_page = Ferrum::Page.new(target_id, same_browser)

# then visit url

page.goto("bla")
same_page.at_css("")
```

But I don't recommend you doing it
