### ISSUE TITLE
Ferrum::BrowserError: No resource with given identifier found

### ISSUE THREAD

**Issue by Valve** [rubycdp/ferrum#40]
When I'm reading network exchange response body, sometimes I get this error:

```
Ferrum::BrowserError: No resource with given identifier found
```

**Comment by route** [comment]
Like we discussed in PM it may happen when you clear network and visit new url. While browser is sending request to a new url the old page is still being processed in the background and requests from the old page may appear in `browser.network`, so next time you iterate over the array besides requests for a new page it may have stale requests for the previous page for which Chrome cannot find the id. Instead of clearing network it's preferable to close the page and context and create new one. This should solve it completely.

**Comment by Nakilon** [comment]
I have the `No resource with given identifier found (Ferrum::BrowserError)` even though the request to the url was surely the only one during the whole browser session (i.e. I don't repeat anything and don't touch it).

The code (based on https://github.com/rubycdp/ferrum/issues/169#issuecomment-948234263) is like this:
```ruby
  node.click  # <a href...> with some JS that initiates the download
  sleep 3
  p browser.network.traffic.select{ |_| "seqdump.cgi" == File.basename(_.request.url) }.last.response.body  # => exception
```
```none
gems/2.3.0/gems/ferrum-0.11/lib/ferrum/browser/client.rb:96:in `raise_browser_error': No resource with given identifier found (Ferrum::BrowserError)
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ferrum-0.11/lib/ferrum/browser/client.rb:48:in `command'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ferrum-0.11/lib/ferrum/page.rb:160:in `command'
	from /Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/ferrum-0.11/lib/ferrum/network/response.rb:58:in `body'
	from ncbi.rb:67:in `block in <main>'
```
