### ISSUE TITLE
How to handle or circumvent Ferrum::BrowserError "Could not compute content quads."?

### ISSUE THREAD

**Issue by alexanderadam** [rubycdp/ferrum#95]
I don't find anything regarding this.

**Comment by route** [comment]
I’m interested in this as well but didn’t have time to investigate, sometimes Chrome cannot get coordinates and I don’t know the reason, as a workaround try getting them with JS and use click coordinates or trigger click.

**Comment by alexanderadam** [comment]
Would you post your equivalent JS content helpers, that you use?

**Comment by route** [comment]
Thanks! Would be awesome

**Comment by Systho** [comment]
@alexanderadam 

Any chance you'd be willing to share your fix and/or your investigation about it ?

**Comment by tlghacc** [comment]
I encountered this error when trying to determine position of a randomly selected link on the page

`link = page.xpath('//a').sample`

Sometimes it worked, sometimes it threw the exception. It turned out the method fails when the link isn't actually visible, for example when it's hidden in a popup menu that only shows when you mouseover some other element

`link.find_position => exception`
`page.mouse.move(x: 115, y:165)`
`link.find_position => coordinates`

I guess it makes sense that an element, which is not visible at the moment, has no coordinates.

**Comment by route** [comment]
@tlghacc I remember a case when a link was visible but Chrome returned "Could not compute content quads" so instead I used `trigger` because `click` didn't work, though I remember clear that the element was clickable for real user in the browser.
