### ISSUE TITLE
`Ferrum::DeadBrowserError` is raised  after running with multiprocess

### ISSUE THREAD

**Issue by kyoshidajp** [rubycdp/ferrum#96]
Hello.

My environments and sample code is here.

```
OS: macOS 0.13.6 (17G8030)
Ruby: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin17]
Gems:
  ferrum 0.8
  parallel 1.19.2
```

```
bundle exec ruby sample.rb
```

```ruby
# sample.rb

require 'ferrum'
require 'parallel'
require 'pry'

browser = Ferrum::Browser.new
browser.goto('https://google.com')

Parallel.each(['1','2']) do |i|
  p i
end

# binding.pry
#browser.restart

browser.goto('https://www.amazon.com/')
```

`browser.goto('https://www.amazon.com/')` is raised `Ferrum::DeadBrowserError`. I checked a browser process after multi processing by `browser.process.pid` and `ps` command at `binding.pry`, then the process is zombie status.

So `browser.restart` to set will work just fine. Parallel with `in_threads` as multi threads mode also will work fine.

I'm not sure if the cause is ferrum, or parallel, or something else. I would like to know if you have any helpful information.

Thanks.

**Comment by sulleh** [comment]
I've actually started to see this issue as well.  I'm using Ferrum 0.8 and without any code changes on my side, it's throwing off the Ferrum::DeadBrowserError in my logging in Sidekiq.

**Comment by route** [comment]
To investigate it turn on FERRUM_DEBUG=true env option and attach log files guys

**Comment by route** [comment]
@kyoshidajp briefly taking a look at parallel gem I guess it forks the process by default, but ferrum keeps websocket connection to Chrome if you have 2 processes that have the same websocket connection to 1 Chrome which one Chrome should send response to? Thus you see dead browser error because one or none gets response from Chrome. To put it simply just don't use it like this or spawn 1 browser and 2 ferrum instances.
